import React, { useState, useEffect, useMemo } from 'react';
import { 
  Copy, RefreshCw, CheckCircle, AlertTriangle, Terminal, Cpu, Zap, Activity, 
  Layout, Monitor, Smartphone, Square, ImageIcon, ChevronDown, Box, 
  Layers, Eye, EyeOff, Pencil, Camera, Crosshair, Lock, Clock, Bot, Globe, 
  ArrowRight, UploadCloud, Siren, Crown, Sparkles, Diamond, ShieldCheck, 
  Type, LayoutGrid, Gem, Network, Download, Component, Trash2, Archive, LogOut, ShieldAlert, UserCheck, Ticket, XCircle, Shield
} from 'lucide-react';

import { initializeApp } from 'firebase/app';
import { getAnalytics } from "firebase/analytics";
import { getFirestore, doc, setDoc, getDoc, query, where, collection, getDocs, updateDoc } from 'firebase/firestore';
import { getAuth, signInWithPopup, onAuthStateChanged, GoogleAuthProvider, signOut } from 'firebase/auth';
import { GoogleGenerativeAI } from "@google/generative-ai";

// --- [CONFIG] FIREBASE ---
const firebaseConfig = {
  apiKey: "AIzaSyChWiNeQ8Myqlfm1QAl1LsPK2a5OGr_M7c",
  authDomain: "nextgen-web-257fb.firebaseapp.com",
  projectId: "nextgen-web-257fb",
  storageBucket: "nextgen-web-257fb.firebasestorage.app",
  messagingSenderId: "778138454377",
  appId: "1:778138454377:web:f7b9b9f0f44e3f577f55f8",
  measurementId: "G-5PP6H4NHQJ"
};

const fbApp = initializeApp(firebaseConfig);
const analytics = getAnalytics(fbApp);
const db = getFirestore(fbApp);
const auth = getAuth(fbApp);
const provider = new GoogleAuthProvider();
const FILE_VERSION = "V.13.48"; 

// --- [MASTER PROTOCOL TRIAL] ---
const MASTER_TRIAL_PROTOCOL = {
  "role": "nextgen_standard",
  "project_type": "standard_infographic",
  "output_settings": { "resolution": "HD", "language": "Indonesian" },
  "branding_footer": { "credit_text": "© NEXTGEN","disclaimer": "Visual generated by NEXTGEN."},
  "strict_visual_policy": { "visible_text_policy": "design_text_only" }
};

// --- [KODE 2: MASTER PROTOCOL ELITE PRO] ---
const MASTER_ELITE_PROTOCOL = {
   "role": "nextgen_ultimate",
   "project_type": "editorial_3D_infographic_template",
   "reusable": true,
    "output_settings": {
    "output_format": "high-resolution vertical infographic poster",
    "aspect_ratio": "9:16",
    "resolution": "8K cinematic grade",
    "language": "Indonesian"},

    "global_visual_logic": {
    "style_adaptive": true,
    "visual_consistency_lock": true,
    "composition_priority": [
    "readability",
    "hierarchy",
    "focus",
    "visual_emotion"]},

    "typography_system": {"anti_blur_mode": true,
    "min_font_render_size": "large-readable",
    "font_render_strategy": "solid_object_typography",
    "stroke_clarity": "high-contrast-edge",
    "depth_isolation": true,
    "font_profiles": {"headline_font": "Custom Display Hybrid — organic curves, bold strokes, cultural-neutral, cinematic weight",
    "subheadline_font": "Expressive Neo-Humanist — semi-rounded, wide aperture, high legibility",
    "body_font": "Experimental Readable Grotesk — soft geometry, thick baseline, anti-noise",
    "caption_font": "Micro-Readable Display — optimized for small size & mobile zoom"}},
    "headline_section": {"headline_text": "","headline_style": {"font_profile": "headline_font","font_weight": "Ultra Bold","alignment": "center","position": "adaptive-top"},"subheadline_text": "",
    "subheadline_style": {"font_profile": "subheadline_font","alignment": "center"}},"main_visual_section": {"visual_concept": "","visual_description": "",
    "visual_style": ["aesthetic collage composition","layered editorial visual","high-detail focal stacking","style follows user input"],
    "camera": {"angle": "adaptive","depth_of_field": "controlled-shallow (text-safe)","lighting": "subject-priority lighting (no text washout)"}},
    "color_palette": {"primary": "","secondary": "","accent": "","background": ""},
    "data_visualization_sections": [{"section_title": "","section_purpose": "","visual_type": "adaptive-infographic",
    "content_points": [{"title": "","description": ""}]}],
    "impact_section": {"section_title": "","layout": "adaptive-grid","impacts": [{"impact_title": "","impact_text": ""}]},
    "artifact_control_system": {"pre_generation_sanity_check": true,"model_specific_prompt_tuning": true,"typography_protection": true,"micro_detail_suppression": true,"selective_regeneration": true},
    "design_details": {"render_quality": "8K cinematic photorealism","edge_definition": "ultra-sharp","noise_control": "clean-output","layer_separation": "strong-depth-hierarchy"},
    "background_design": {"background_type": "","decorative_elements": "",
    "branding_footer": {"credit_text": "© NEXTGEN","disclaimer": "Visual generated by NEXTGEN."},
    "ai_model_recommendation": ["Midjourney v6","Midjourney v6.1","DALL·E 3","DALL·E (High Fidelity Mode)","Stable Diffusion XL (SDXL)","SDXL Refiner","SDXL Turbo","Ideogram 2.0","Ideogram Typography Mode","Leonardo AI","Leonardo Kino XL","Firefly Image 3","Firefly Ultra Detail","Playground v2.5","Runway Gen-Image","Krea AI","Fooocus","ComfyUI Custom Pipeline","Blender Cycles (AI-assisted)","Cinema 4D + AI Render Assist","Octane Render AI Denoise"],
    "negative_prompt": ["blurry text","thin typography","low contrast text","text merged with background","artifact noise","over-sharpening","flat illustration","cartoon style","messy layout","unreadable small text"],"strict_visual_policy": {"visible_text_policy": "design_text_only","violation_handling": "auto-clean-and-regenerate"}}};

const INITIAL_CREATIVE = [
  { id: 'analytical_exploded_diagram', label: 'Analytical Exploded Diagram', desc: 'Cocok untuk: edukasi produk, penjelasan mekanisme, presentasi teknis, poster edukatif', type: 'layers' },
  { id: 'xray_layer_model', label: 'X-Ray Layer Model', desc: 'Cocok untuk: visual internal produk, teknologi, anatomi sistem, poster sains/tech', type: 'eye' },
  { id: 'blueprint_technical', label: 'Blueprint Technical', desc: 'Cocok untuk: engineering, arsitektur, produk hardware, poster teknis & proposal', type: 'pencil' },
  { id: 'hud_futuristic_interface', label: 'HUD Futuristic Interface', desc: 'Cocok untuk: poster teknologi, UI concept, AI showcase, visual data futuristik', type: 'crosshair' },
  { id: 'cinematic_editorial_3d', label: 'Cinematic Editorial 3D', desc: 'Cocok untuk: poster promosi, branding produk, campaign visual, presentasi premium', type: 'camera' },
  { id: 'ultra_clean_infographic', label: 'Ultra Clean Infographic', desc: 'Cocok untuk: poster informasi, data statistik, edukasi publik, corporate content', type: 'layout' },
  { id: 'structural_logic_mapping', label: 'Structural Logic Mapping', desc: 'Cocok untuk: flow sistem, mind map visual, strategi bisnis, poster penjelasan konsep', type: 'network' },
  { id: 'editorial_cutaway_perspective', label: 'Editorial Cutaway Perspective', desc: 'Cocok untuk: produk kompleks, otomotif, mesin, poster edukasi premium', type: 'split' },
  { id: 'precision_grid_system', label: 'Precision Grid System', desc: 'Cocok untuk: branding profesional, poster korporat, layout minimal & rapi', type: 'grid' },
  { id: 'material_truth_visualization', label: 'Material Truth Visualization', desc: 'Cocok untuk: showcase material, produk fisik, poster industrial & desain produk', type: 'box' }
];

const INITIAL_ELITE = [
  { id: 'glassmorphism_pro', label: 'Glassmorphism Pro', desc: 'Cocok untuk: poster startup, tech launch, UI branding modern', type: 'gem' },
  { id: 'liquid_glass_transparency', label: 'Liquid Glass Transparency', desc: 'Cocok untuk: poster futuristik, AI, visual premium yang terasa hidup', type: 'droplet' },
  { id: 'neural_data_visualization', label: 'Neural Data Visualization', desc: 'Cocok untuk: AI, data science, teknologi otak, poster konsep pintar', type: 'network' },
  { id: 'holographic_projection_style', label: 'Holographic Projection Style', desc: 'Cocok untuk: poster event futuristik, sci-fi, teknologi masa depan', type: 'scan' },
  { id: 'system_ui_render_mode', label: 'System UI Render Mode', desc: 'Cocok untuk: AI dashboard, visual sistem, poster produk digital', type: 'terminal' },
  { id: 'synthetic_reality_render', label: 'Synthetic Reality Render', desc: 'Cocok untuk: konsep visioner, campaign kreatif, poster eksperimental', type: 'sparkles' },
  { id: 'meta_architecture_visualization', label: 'Meta-Architecture Visualization', desc: 'Cocok untuk: arsitektur konseptual, metaverse, poster ide besar', type: 'component' },
  { id: 'quantum_layer_visualization', label: 'Quantum Layer Visualization', desc: 'Cocok untuk: konsep abstrak, teknologi canggih, poster futuristik ekstrem', type: 'hex' },
  { id: 'invisible_material_design', label: 'Invisible Material Design', desc: 'Cocok untuk: desain konseptual, luxury tech, poster minimal futuristik', type: 'ghost' },
  { id: 'post_human_interface_aesthetic', label: 'Post-Human Interface Aesthetic', desc: 'Cocok untuk: AI generasi lanjut, sci-fi, poster spekulatif', type: 'bot' },
  { id: 'adaptive_reality_interface', label: 'Adaptive Reality Interface', desc: 'Cocok untuk: produk AI, sistem pintar, poster teknologi adaptif', type: 'refresh' },
  { id: 'translucent_physics_render', label: 'Translucent Physics Render', desc: 'Cocok untuk: visual material canggih, teknologi sains, poster futuristik realistis', type: 'wind' },
  { id: 'cognitive_hud_overlay', label: 'Cognitive HUD Overlay', desc: 'Cocok untuk: AI vision, analitik, poster sistem cerdas', type: 'activity' },
  { id: 'temporal_layer_visualization', label: 'Temporal Layer Visualization', desc: 'Cocok untuk: storytelling waktu, roadmap, poster konsep masa depan', type: 'clock' },
  { id: 'post_digital_minimalism', label: 'Post-Digital Minimalism', desc: 'Cocok untuk: branding premium, poster luxury, desain dewasa & tenang', type: 'circle' },
  { id: 'sentient_system_aesthetic', label: 'Sentient System Aesthetic', desc: 'Cocok untuk: AI visioner, sistem sadar, poster “beyond human”', type: 'cpu' }
];

const App = () => {
  const [formData, setFormData] = useState({ title: '', description: '', aspectRatio: '9:16' });
  const [generatedPayload, setGeneratedPayload] = useState(null);
  const [history, setHistory] = useState([]);
  const [isLoading, setIsLoading] = useState(false);
  const [activePack, setActivePack] = useState('creative');
  const [selectedStyle, setSelectedStyle] = useState(INITIAL_CREATIVE[0]);
  const [showStyleDropdown, setShowStyleDropdown] = useState(false);
  const [isDevMode, setIsDevMode] = useState(false);
  const [toast, setToast] = useState(null);
  const [isLoggedIn, setIsLoggedIn] = useState(false); 
  const [premiumToken, setPremiumToken] = useState(""); 
  const [isPremium, setIsPremium] = useState(false); 
  const [isApproved, setIsApproved] = useState(false); 
  const [trialDays, setTrialDays] = useState(30);
  const [genCount, setGenCount] = useState(0); 
  const [showToken, setShowToken] = useState(false);
  const [authLoading, setAuthLoading] = useState(true);

  const geminiApiKey = "AIzaSyAN6Cd5vB8D7QrQ91P76NxDgXxqpqe8HJg";

  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, async (user) => {
      if (user) {
        const ADMIN_EMAIL = "sdkurniawan5@gmail.com"; 
        const userRef = doc(db, "users", user.uid);
        const userSnap = await getDoc(userRef);
        if (userSnap.exists()) {
          const userData = userSnap.data();
          setIsLoggedIn(true);
          setIsPremium(userData.isPremium);
          setIsApproved(userData.isApproved || false);
          const today = new Date().toDateString();
          if (userData.lastGenDate !== today) {
            await updateDoc(userRef, { dailyCount: 0, lastGenDate: today });
            setGenCount(0);
          } else {
            setGenCount(userData.dailyCount || 0);
          }
          if (user.email === ADMIN_EMAIL) {
            setIsDevMode(true); 
            setIsPremium(true);
            setIsApproved(true);
          }
          const joinDate = new Date(userData.joinDate);
          const now = new Date();
          const diffDays = Math.ceil(Math.abs(now - joinDate) / (1000 * 60 * 60 * 24)); 
          const remainingDays = 30 - (diffDays - 1);
          const finalDays = remainingDays > 0 ? remainingDays : 0;
          setTrialDays(finalDays);
          if (!userData.isPremium && finalDays === 0) showToast("TRIAL EXPIRED. PLEASE ACTIVATE PREMIUM", "error");
        }
      } else { setIsLoggedIn(false); }
      setAuthLoading(false);
    });
    const saved = localStorage.getItem('nxg_archives');
    if (saved) setHistory(JSON.parse(saved));
    return () => unsubscribe();
  }, []);

  const showToast = (message, type = 'info') => { setToast({ message, type }); setTimeout(() => setToast(null), 3000); };

  const handleLogin = async () => {
    try {
      const result = await signInWithPopup(auth, provider);
      if (result.user) {
        const userRef = doc(db, "users", result.user.uid);
        const userSnap = await getDoc(userRef);
        if (!userSnap.exists()) {
          await setDoc(userRef, { name: result.user.displayName, email: result.user.email, joinDate: new Date().toISOString(), isPremium: false, isApproved: false });
          setIsApproved(false);
        } else { setIsApproved(userSnap.data().isApproved || false); }
        setIsLoggedIn(true);
      }
    } catch (error) { showToast("LOGIN ERROR", "error"); }
  };

  const validateToken = async () => {
    if (!premiumToken) { showToast("MOHON MASUKKAN TOKEN", "error"); return; }
    try {
      const q = query(collection(db, "system_keys"), where("premium_token", "==", premiumToken));
      const querySnapshot = await getDocs(q);
      if (querySnapshot.empty) { showToast("TOKEN TIDAK VALID", "error"); return; }
      const tokenDoc = querySnapshot.docs[0];
      const tokenData = tokenDoc.data();
      const currentUserUid = auth.currentUser.uid;
      if (tokenData.isUsed && tokenData.ownerUid !== currentUserUid) { showToast("TOKEN SUDAH DIGUNAKAN AKUN LAIN", "error"); return; }
      setIsPremium(true); setIsDevMode(true); setIsApproved(true); showToast("PREMIUM DIAKTIFKAN!", "success");
      await updateDoc(doc(db, "system_keys", tokenDoc.id), { isUsed: true, ownerUid: currentUserUid });
      await updateDoc(doc(db, "users", currentUserUid), { isPremium: true, isApproved: true });
    } catch (error) { showToast("GAGAL VERIFIKASI SISTEM", "error"); }
  };

  // --- [ADMIN COMMAND FUNCTIONS] ---
  const fetchPremiumReport = async () => {
    showToast("FETCHING REPORT...", "info");
    try {
      const q = query(collection(db, "system_keys"), where("isUsed", "==", true));
      const querySnapshot = await getDocs(q);
      let reportText = "📊 SALES REPORT\n====================\n\n";
      for (const tokenDoc of querySnapshot.docs) {
        const info = tokenDoc.data();
        const uSnap = await getDoc(doc(db, "users", info.ownerUid));
        reportText += `👤 ${uSnap.exists() ? uSnap.data().name : "Unknown"}\n🔑 ${info.premium_token}\n--------------------\n`;
      }
      alert(reportText || "Belum ada penjualan.");
      showToast("REPORT GENERATED", "success");
    } catch (error) { showToast("REPORT ERROR", "error"); }
  };

  const fetchUserList = async () => {
    showToast("FETCHING USERS...", "info");
    try {
      const querySnapshot = await getDocs(collection(db, "users"));
      let userText = "👥 USER LIST\n====================\n\n";
      querySnapshot.forEach((doc) => {
        const data = doc.data();
        userText += `${data.isPremium ? "💎" : "🆓"} ${data.name}\n📧 ${data.email}\nAcc: ${data.isApproved ? "✅" : "❌"} | Gen: ${data.dailyCount}/10\n--------------------\n`;
      });
      alert(userText);
      showToast("DONE", "success");
    } catch (error) { showToast("FETCH ERROR", "error"); }
  };

  const viewAvailableKeys = async () => {
    showToast("FETCHING STOCK...", "info");
    try {
      const q = query(collection(db, "system_keys"), where("isUsed", "==", false));
      const querySnapshot = await getDocs(q);
      const availableTokens = querySnapshot.docs.slice(0, 50).map(d => d.data().premium_token);
      if (availableTokens.length === 0) { alert("Stok kosong!"); return; }
      navigator.clipboard.writeText(availableTokens.join("\n"));
      alert("🔑 READY TO SELL (50 STOK):\n\n" + availableTokens.join("\n") + "\n\n✅ AUTO-COPIED!");
      showToast("STOCK LOADED", "success");
    } catch (error) { showToast("STOCK ERROR", "error"); }
  };

  const approveUserTrial = async (targetEmail) => {
    if (!targetEmail) { alert("Format: NXG-ACC-USER:email"); return; }
    try {
      const q = query(collection(db, "users"), where("email", "==", targetEmail.trim()));
      const querySnapshot = await getDocs(q);
      if (querySnapshot.empty) { alert("Email tidak ditemukan!"); return; }
      await updateDoc(doc(db, "users", querySnapshot.docs[0].id), { isApproved: true });
      alert(`✅ APPROVED: ${targetEmail}`);
    } catch (error) { showToast("ERROR", "error"); }
  };

  const generateBulkTokens = async () => {
    if (!window.confirm("Cetak 50 token baru?")) return;
    try {
      const tokens = [];
      for (let i = 0; i < 50; i++) {
        const p1 = Math.random().toString(36).substring(2, 6).toUpperCase();
        const p2 = Math.random().toString(36).substring(2, 6).toUpperCase();
        tokens.push(setDoc(doc(collection(db, "system_keys")), { premium_token: `NXG-${p1}-${p2}`, isUsed: false, ownerUid: "", createdAt: new Date().toISOString() }));
      }
      await Promise.all(tokens);
      alert("✅ 50 Token baru ditambahkan.");
    } catch (err) { showToast("FAILED", "error"); }
  };

  const deleteHistory = (id) => {
    const updatedHistory = history.filter(item => item.id !== id);
    setHistory(updatedHistory);
    localStorage.setItem('nxg_archives', JSON.stringify(updatedHistory));
    showToast("ARCHIVE DELETED", "error");
  };

  const handleLogout = async () => { await signOut(auth); setIsLoggedIn(false); showToast("LOGGED OUT", "info"); };

// --- [NEURAL ADMIN COMMAND CENTER] ---
  const runAdminCommand = async () => {
    const cmd = window.prompt("ENTER ADMIN COMMAND (STOK, REPORT, GEN, ACC:email):");
    if (!cmd) return;

    const command = cmd.trim();

    // Laporan Penjualan
    if (command === "REPORT") {
      showToast("FETCHING REPORT...", "info");
      const q = query(collection(db, "system_keys"), where("isUsed", "==", true));
      const snap = await getDocs(q);
      let txt = "📊 SALES REPORT\n\n";
      for (const d of snap.docs) { txt += `🔑 ${d.data().premium_token} (USED)\n---\n`; }
      alert(txt || "Belum ada penjualan.");
    } 
    
    // Cek Stok Token (50 Biji + Auto Copy)
    else if (command === "STOK") {
      showToast("FETCHING STOCK...", "info");
      const q = query(collection(db, "system_keys"), where("isUsed", "==", false));
      const snap = await getDocs(q);
      const keys = snap.docs.slice(0, 50).map(d => d.data().premium_token);
      if (keys.length === 0) { alert("Stok kosong!"); return; }
      navigator.clipboard.writeText(keys.join("\n"));
      alert("🔑 READY TO SELL (50 STOK COPIED):\n\n" + keys.join("\n"));
    } 
    
    // Cetak Token Baru
    else if (command === "GEN") {
      if (!window.confirm("Generate 50 token baru?")) return;
      showToast("GENERATING...", "info");
      for (let i = 0; i < 50; i++) {
        const p = () => Math.random().toString(36).substring(2, 6).toUpperCase();
        await setDoc(doc(collection(db, "system_keys")), { 
          premium_token: `NXG-${p()}-${p()}`, 
          isUsed: false, 
          ownerUid: "", 
          createdAt: new Date().toISOString() 
        });
      }
      alert("✅ 50 Token berhasil masuk brankas.");
    } 
    
    // Approve User Trial Manual
    else if (command.startsWith("ACC:")) {
      const email = command.split(":")[1];
      showToast("APPROVING...", "info");
      const q = query(collection(db, "users"), where("email", "==", email.trim()));
      const snap = await getDocs(q);
      if (snap.empty) { alert("Email user tidak ditemukan!"); return; }
      await updateDoc(doc(db, "users", snap.docs[0].id), { isApproved: true });
      alert("✅ APPROVED: " + email);
    } 
    
    else {
      alert("COMMAND UNKNOWN!");
    }
  };

  const handleGenerate = async () => {
    // --- [PROTEKSI AKSES USER - KODE 2] ---
    if (!isApproved) { 
      showToast("ACCOUNT PENDING VERIFICATION", "error"); 
      return; 
    }
    
    if (!isPremium) {
      if (trialDays === 0) { 
        showToast("TRIAL EXPIRED! ORDER TOKEN TO CONTINUE", "error"); 
        return; 
      }
      if (genCount >= 10) { 
        showToast("DAILY LIMIT REACHED (10/10).", "error"); 
        return; 
      }
    }

    if (!formData.title || !formData.description) { 
      showToast("DATA TIDAK LENGKAP!", "error"); 
      return; 
    }
    
    setIsLoading(true);
    try {
      // --- [AI PROTOCOL - KODE 1] ---
      const genAI = new GoogleGenerativeAI(geminiApiKey);
      const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash-preview-09-2025" });
      // 1. Baris tambahan: Cek status user (isPremium) buat pilih otak AI
      const activeMaster = isPremium ? MASTER_ELITE_PROTOCOL : MASTER_TRIAL_PROTOCOL;
      
      // 2. Baris promptText yang diupdate pake variabel activeMaster
      const promptText = `Generate JSON prompt. IDENTITY: "${formData.title}", CONTEXT: "${formData.description}", STYLE: "${selectedStyle.label}", MASTER: ${JSON.stringify(activeMaster)}`;
      
      const result = await model.generateContent(promptText);
      const output = result.response.text();

      if (output) {
        const cleanJsonRaw = output.replace(/```json|```/g, "");
        const cleanJson = JSON.stringify(JSON.parse(cleanJsonRaw), null, 2);
        setGeneratedPayload(cleanJson);

        const newEntry = { 
          id: Date.now(), 
          time: new Date().toLocaleTimeString(), 
          title: formData.title, 
          style: selectedStyle.label, 
          data: cleanJson 
        };
        
        setHistory([newEntry, ...history.slice(0, 9)]);
        localStorage.setItem('nxg_archives', JSON.stringify([newEntry, ...history.slice(0, 9)]));
        
        if (!isPremium) {
          const newCount = genCount + 1;
          setGenCount(newCount);
          const userRef = doc(db, "users", auth.currentUser.uid);
          await updateDoc(userRef, { dailyCount: newCount, lastGenDate: new Date().toDateString() });
        }

        showToast("NEURAL SYNC COMPLETE", "success");
      }
    } catch (err) { 
      console.error(err);
      showToast("API ERROR: RE-CHECK KEY", "error"); 
    } finally { 
      setIsLoading(false); 
    }
  };

  const getIcon = (type) => {
    const p = { className: "w-4 h-4" };
    switch(type) {
      case 'layers': return <Layers {...p} />;
      case 'crosshair': return <Crosshair {...p} />;
      case 'camera': return <Camera {...p} />;
      case 'gem': return <Gem {...p} className="text-amber-500" />;
      case 'cpu': return <Cpu {...p} className="text-amber-500" />;
      default: return <Zap {...p} />;
    }
  };

  if (authLoading) return <div className="min-h-screen bg-[#010208] flex items-center justify-center font-mono text-cyan-500"><RefreshCw className="animate-spin" size={32} /></div>;

  return (
    <div className={`min-h-screen transition-all duration-1000 ${isPremium ? 'bg-[#0a0801]' : 'bg-[#010208]'} text-white p-4 md:p-8 font-mono relative overflow-x-hidden`}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Orbitron:wght@900&display=swap');
        .custom-scrollbar::-webkit-scrollbar { width: 4px; }
        .custom-scrollbar::-webkit-scrollbar-thumb { background: ${isPremium ? '#f59e0b' : '#065f46'}; border-radius: 10px; }
        .dashboard-background { position: fixed; top: 0; left: 0; width: 100%; height: 100%; z-index: 0; background-image: linear-gradient(${isPremium ? 'rgba(245, 158, 11, 0.05)' : 'rgba(30, 58, 138, 0.1)'} 1px, transparent 1px), linear-gradient(90deg, ${isPremium ? 'rgba(245, 158, 11, 0.05)' : 'rgba(30, 58, 138, 0.1)'} 1px, transparent 1px); background-size: 40px 40px; pointer-events: none; }
        .premium-glow { position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); width: 800px; height: 800px; background: radial-gradient(circle, rgba(245, 158, 11, 0.08) 0%, transparent 70%); z-index: 0; pointer-events: none; display: ${isPremium ? 'block' : 'none'}; }
        .nxg-animated-logo { font-family: 'Orbitron', sans-serif; font-size: 70px; font-weight: 900; fill: transparent; stroke: ${isPremium ? '#f59e0b' : '#1e3a8a'}; stroke-width: 1.5px; stroke-dasharray: 600; stroke-dashoffset: 600; animation: stroke-flow 6s linear infinite; text-transform: uppercase; }
        @keyframes stroke-flow { 0% { stroke-dashoffset: 600; stroke: ${isPremium ? '#92400e' : '#1e3a8a'}; fill: transparent; } 30% { stroke: ${isPremium ? '#f59e0b' : '#00d1ff'}; filter: drop-shadow(0 0 15px ${isPremium ? '#f59e0b' : '#00d1ff'}); } 50% { fill: ${isPremium ? 'rgba(245, 158, 11, 0.1)' : 'rgba(0, 209, 255, 0.1)'}; } 100% { stroke-dashoffset: 0; stroke: ${isPremium ? '#92400e' : '#1e3a8a'}; } }
        .premium-border { border: 1px solid ${isPremium ? 'rgba(245, 158, 11, 0.3)' : 'rgba(30, 58, 138, 0.2)'}; box-shadow: ${isPremium ? '0 0 20px rgba(245, 158, 11, 0.1)' : 'none'}; }
        .gold-text { background: linear-gradient(to right, #f59e0b, #fbbf24, #f59e0b); -webkit-background-clip: text; -webkit-text-fill-color: transparent; animation: gold-flow 3s linear infinite; background-size: 200% auto; }
        @keyframes gold-flow { to { background-position: 200% center; } }
        .price-glow { animation: price-highlight 1.5s ease-in-out infinite; }
        @keyframes price-highlight { 0%, 100% { box-shadow: 0 0 5px rgba(245, 158, 11, 0.3); transform: scale(1); } 50% { box-shadow: 0 0 25px rgba(245, 158, 11, 0.7); transform: scale(1.05); } }
      `}</style>
      <div className="dashboard-background"></div><div className="premium-glow"></div>
      <div className="relative z-10">
        {!isLoggedIn ? (
          <div className="flex flex-col items-center justify-center h-[80vh] space-y-8 animate-in fade-in zoom-in duration-700">
            <div className="text-center"><div className="relative mb-2 flex justify-center"><svg className="w-[300px] md:w-[600px] h-24 md:h-32" viewBox="0 0 500 100"><text x="50%" y="50%" textAnchor="middle" dominantBaseline="middle" className="nxg-animated-logo">NEXTGEN</text></svg></div><p className="text-slate-500 tracking-[0.4em] uppercase text-[10px] mt-4 font-bold">Neural Protocol Standby</p></div>
            <button onClick={handleLogin} className="group bg-white text-black font-black px-12 py-4 rounded-full hover:bg-cyan-500 transition-all flex items-center gap-3 tracking-[0.2em] text-xs shadow-[0_0_20px_rgba(255,255,255,0.1)]"><Globe size={18} /> SIGN IN WITH GOOGLE</button>
          </div>
        ) : !isApproved ? (
          <div className="flex flex-col items-center justify-center min-h-[90vh] space-y-10 text-center px-6 animate-in fade-in zoom-in duration-1000">
            <div className="space-y-2"><ShieldAlert size={80} className="text-cyan-500 mx-auto mb-4 animate-pulse" /><h2 className="text-3xl font-black tracking-[0.3em] text-white uppercase">Neural Verification</h2><p className="text-slate-500 text-[10px] tracking-[0.5em] font-bold uppercase italic">Select access protocol</p></div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 w-full max-w-5xl">
              <div className="bg-slate-900/30 border border-slate-800 p-8 rounded-[2.5rem] hover:border-cyan-500/50 group relative overflow-hidden text-left flex flex-col justify-between">
                <div className="absolute -right-10 top-6 rotate-45 bg-cyan-500 text-black text-[10px] font-black px-12 py-1 tracking-tighter uppercase">FREE ACCESS</div>
                <div className="space-y-6"><div className="flex items-center justify-between"><div className="w-12 h-12 bg-cyan-950/30 rounded-2xl flex items-center justify-center text-cyan-400"><UserCheck size={24} /></div><span className="text-[8px] font-black px-3 py-1 bg-cyan-500/10 text-cyan-500 rounded-full tracking-widest uppercase">Limited</span></div>
                <div><h3 className="text-xl font-black text-white tracking-widest uppercase mb-2">Trial Access</h3><p className="text-slate-500 text-[9px] uppercase tracking-wider mb-6">Evaluation Protocol v1.0</p>
                <div className="space-y-3 border-t border-slate-800/50 pt-6">{[{l:'30 Days Access',a:true},{l:'Standard Styles',a:true},{l:'Manual Verification',a:true}].map((b,i)=>(<div key={i} className="flex items-center gap-3">{b.a?<CheckCircle size={12} className="text-cyan-500"/>:<XCircle size={12} className="text-red-500/50"/>}<span className={`text-[10px] font-bold uppercase tracking-widest ${b.a?'text-slate-300':'text-slate-700'}`}>{b.l}</span></div>))}</div></div></div>
                <button onClick={() => window.open(`https://wa.me/6285129070307?text=Halo%20Admin,%20tolong%20verifikasi%20akun%20saya.%20Email:%20${auth.currentUser.email}`, '_blank')} className="mt-10 w-full bg-white text-black py-4 rounded-xl text-[10px] font-black hover:bg-cyan-500 transition-all tracking-[0.2em] uppercase">Request Verification</button>
              </div>
              <div className="bg-amber-950/10 border border-amber-900/30 p-8 rounded-[2.5rem] hover:border-amber-500/50 group relative overflow-hidden text-left flex flex-col justify-between">
                <div className="space-y-6"><div className="flex items-center justify-between"><div className="w-12 h-12 bg-amber-950/30 rounded-2xl flex items-center justify-center text-amber-500"><Ticket size={24} /></div><div className="price-glow bg-amber-500 text-black px-4 py-2 rounded-xl border-2 border-amber-400"><div className="flex items-center gap-2"><span className="text-[9px] font-black line-through opacity-50">Rp 499.999</span><span className="text-[8px] bg-red-600 text-white px-1.5 py-0.5 rounded-md font-black animate-bounce tracking-tighter uppercase text-[6px]">DISKON 90%</span></div><div className="text-[12px] font-black tracking-tighter animate-pulse uppercase">NOW ONLY Rp. 49.999</div></div></div>
                <div><h3 className="text-xl font-black text-amber-500 tracking-widest uppercase mb-2 italic">Elite Pro</h3><p className="text-slate-500 text-[9px] uppercase tracking-wider mb-6">Supreme Intelligence Access</p>
                <div className="space-y-3 border-t border-slate-800/50 pt-6">{['Lifetime Access', 'All Premium Styles', 'Instant AI Unlock', 'Priority AI Speed'].map((b,i)=>(<div key={i} className="flex items-center gap-3"><CheckCircle size={12} className="text-amber-500"/><span className="text-[10px] font-bold uppercase tracking-widest text-amber-100">{b}</span></div>))}</div></div></div>
                <div className="mt-8 space-y-3">
                  <div className="bg-black/40 border border-amber-900/30 p-1.5 rounded-xl flex gap-2">
                    <input type="text" placeholder="ENTER TOKEN..." className="bg-transparent border-none outline-none text-[10px] pl-3 w-full uppercase font-black tracking-widest text-amber-500 placeholder:text-amber-900" value={premiumToken} onChange={(e) => setPremiumToken(e.target.value)} />
                    <button onClick={validateToken} className="bg-amber-600 hover:bg-amber-500 text-black px-4 py-2 rounded-lg text-[9px] font-black transition-all">UNLOCK</button>
                    <button onClick={() => window.open(`https://wa.me/6285129070307?text=Halo%20Admin%20Nextgen,%20saya%20mau%20order%20token%20premium.%20Email:%20${auth.currentUser.email}`, '_blank')} className="bg-white hover:bg-slate-200 text-black px-4 py-2 rounded-lg text-[9px] font-black transition-all">GET TOKEN</button>
                  </div>
                </div>
              </div>
            </div>
            <button onClick={handleLogout} className="text-slate-600 text-[10px] hover:text-white transition-colors tracking-widest flex items-center gap-2 uppercase"><LogOut size={12} /> Sign out of system</button>
          </div>
        ) : (
          <div className="animate-in fade-in slide-in-from-bottom-4 duration-1000">
            <div className="w-full mx-auto flex justify-between items-center mb-10 px-6">
              <h1 className="nxg-logo text-4xl tracking-tighter"></h1>
              <div className="flex items-center gap-4">
                {isDevMode && (
    <button 
      onClick={runAdminCommand} 
      className="p-2 bg-red-900/20 border border-red-500/30 text-red-500 rounded-full hover:bg-red-600 hover:text-white transition-all shadow-lg"
    >
      <Shield size={16} />
    </button>
  )}
                {!isPremium && <div className="flex gap-2"><div className="text-[9px] font-black text-cyan-500 bg-cyan-950/20 px-4 py-2 rounded-full border border-cyan-500/30 uppercase tracking-widest">Trial: {trialDays} Days</div><button onClick={() => window.open(`https://wa.me/6285129070307?text=Halo%20Admin,%20mau%20order%20premium.%20Email:%20${auth.currentUser.email}`, '_blank')} className="bg-amber-600 hover:bg-amber-500 text-black px-4 py-2 rounded-full text-[9px] font-black transition-all uppercase">Buy Token</button></div>}
                {isPremium && <div className="flex items-center gap-3 text-amber-500 font-black text-[9px] tracking-[0.3em] bg-amber-950/20 px-6 py-2 rounded-full border border-amber-500/30 shadow-[0_0_15px_rgba(245,158,11,0.2)]"><Crown size={14} className="animate-bounce" /><span className="gold-text uppercase">Elite Access Active</span></div>}
                <button onClick={handleLogout} className="p-2 text-slate-500 hover:text-white transition-colors"><LogOut size={16} /></button>
              </div>
            </div>
            <div className="w-full grid grid-cols-1 lg:grid-cols-12 gap-6 items-start px-2 md:px-10 justify-items-stretch">
              <div className="lg:col-span-12 w-full text-center mb-10 px-4">
                <div className={`text-[10px] font-black tracking-[0.4em] mb-2 ${isPremium ? 'gold-text' : 'text-cyan-500'}`}>{FILE_VERSION}</div>
                <div className="relative mb-2 flex justify-center"><svg className="w-[280px] md:w-[500px] h-20 md:h-28" viewBox="0 0 500 100"><text x="50%" y="50%" textAnchor="middle" dominantBaseline="middle" className="nxg-animated-logo">NEXTGEN</text></svg></div>
                <p className="text-slate-500 tracking-[0.4em] uppercase text-[10px] font-bold italic">{isPremium ? 'ULTIMATE // ELITE SUPREME INTELLIGENCE' : 'ultimate // elite pro intelligence'}</p>
              </div>
              <div className="lg:col-span-3 w-full">
                <div className="mb-6 p-6 rounded-[2rem] bg-slate-900/40 backdrop-blur-xl premium-border">
                  <div className="flex items-center justify-between mb-6"><span className="text-[9px] font-black uppercase tracking-[0.2em] text-slate-500">Access Monitor</span><div className={`px-3 py-1 rounded-full text-[8px] font-black uppercase ${isPremium ? 'bg-amber-500 text-black shadow-[0_0_10px_rgba(245,158,11,0.5)]' : 'bg-cyan-500/20 text-cyan-400 border border-cyan-500/30'}`}>{isPremium ? 'Elite Pro' : 'Evaluation'}</div></div>
                  <div className="space-y-4">
                    <div className="flex items-center justify-between"><div className="flex items-center gap-3"><LayoutGrid size={14} className={isPremium ? "text-amber-500" : "text-cyan-400"} /><span className={`text-[10px] font-black uppercase tracking-widest ${isPremium ? 'text-amber-100' : 'text-slate-300'}`}>Creative Feature</span></div><CheckCircle size={16} className={isPremium ? "text-amber-500" : "text-emerald-500"} /></div>
                    <div className="flex items-center justify-between"><div className="flex items-center gap-3"><Gem size={14} className={isPremium ? "text-amber-500" : "text-slate-700"} /><span className={`text-[10px] font-black uppercase tracking-widest ${isPremium ? 'text-white' : 'text-slate-700'}`}>Elite Feature</span></div>{isPremium ? <CheckCircle size={16} className="text-amber-500" /> : <XCircle size={16} className="text-red-500/50" />}</div>
                    <div className="flex items-center justify-between pt-2 border-t border-slate-800/50"><div className="flex items-center gap-3"><Activity size={14} className={isPremium ? "text-amber-500" : "text-cyan-400"} /><span className={`text-[10px] font-black uppercase tracking-widest ${isPremium ? 'text-amber-100' : 'text-slate-300'}`}>Daily Limit</span></div><span className={`text-[10px] font-black ${isPremium ? 'text-amber-500' : (genCount >= 8 ? 'text-red-500' : 'text-cyan-500')}`}>{isPremium ? 'UNLIMITED' : `${genCount}/10`}</span></div>
                  </div>
                </div>
                <div className="bg-slate-900/20 p-6 rounded-[2.5rem] backdrop-blur-3xl shadow-2xl premium-border">
                  <div className={`flex items-center gap-3 mb-8 border-b ${isPremium ? 'border-amber-900/50 text-amber-500' : 'border-slate-900 text-cyan-400'} pb-4`}><Terminal size={16} /> <h2 className="text-[10px] font-black uppercase tracking-[0.3em]">Neural Console</h2></div>
                  <div className={`flex p-1 ${isPremium ? 'bg-amber-950/20 border-amber-900/30' : 'bg-slate-900/50 border-slate-800'} rounded-xl border mb-8`}>
                    <button onClick={() => setActivePack('creative')} className={`flex-1 py-2 rounded-lg text-[8px] font-black uppercase transition-all ${activePack === 'creative' ? (isPremium ? 'bg-amber-500 text-black' : 'bg-cyan-950/50 text-cyan-400 border border-cyan-500/30') : 'text-slate-500'}`}>Creative</button>
                    <button onClick={() => isDevMode ? setActivePack('elite') : showToast("LOCKED", "error")} className={`flex-1 py-2 rounded-lg text-[8px] font-black uppercase flex items-center justify-center gap-2 transition-all ${activePack === 'elite' ? (isPremium ? 'bg-amber-500 text-black shadow-lg' : 'bg-amber-500 text-black shadow-lg') : 'text-slate-500'}`}>{isDevMode ? <Crown size={10}/> : <Lock size={10}/>} Elite</button>
                  </div>
                  <div className="space-y-6 text-left">
                    <div className="space-y-2"><label className={`text-[9px] font-black uppercase tracking-[0.2em] ml-2 ${isPremium ? 'text-amber-500' : 'text-cyan-400'}`}>IDENTITY NAME</label><div className={`${isPremium ? 'bg-amber-950/10 border-amber-900/30' : 'bg-cyan-950/20 border-slate-800/50'} p-2 rounded-2xl border`}><input className="w-full bg-black/40 border border-slate-800 rounded-xl px-4 py-3 text-[11px] outline-none uppercase text-white" placeholder="Brand Name..." value={formData.title} onChange={(e) => setFormData({...formData, title: e.target.value})} /></div></div>
                    <div className="space-y-2"><label className={`text-[9px] font-black uppercase tracking-[0.2em] ml-2 ${isPremium ? 'text-amber-500' : 'text-cyan-400'}`}>CONTEXT DESCRIPTION</label><div className={`${isPremium ? 'bg-amber-950/10 border-amber-900/30' : 'bg-cyan-950/20 border-slate-800/50'} p-2 rounded-2xl border`}><textarea className="w-full bg-black/40 border border-slate-800 rounded-xl px-4 py-3 text-[11px] outline-none h-24 resize-none uppercase text-white" placeholder="Context Description..." value={formData.description} onChange={(e) => setFormData({...formData, description: e.target.value})} /></div></div>
                    <div className="relative"><div onClick={() => setShowStyleDropdown(!showStyleDropdown)} className={`bg-black/40 border ${isPremium ? 'border-amber-900/50' : 'border-slate-800'} rounded-xl px-4 py-3 flex items-center justify-between cursor-pointer text-[10px] uppercase font-bold`}><span className="truncate">{selectedStyle.label}</span><ChevronDown size={14} /></div>
                      {showStyleDropdown && (<div className="absolute bottom-full left-0 w-full z-50 bg-[#0a0c10] border border-slate-800 rounded-xl p-2 max-h-48 overflow-auto mb-2 custom-scrollbar">{(activePack === 'creative' ? INITIAL_CREATIVE : INITIAL_ELITE).map(s => (<div key={s.id} onClick={() => { setSelectedStyle(s); setShowStyleDropdown(false); }} className={`p-2 hover:bg-${isPremium ? 'amber-600' : 'cyan-600'} rounded-lg cursor-pointer flex items-center gap-3 text-[10px] uppercase font-bold`}>{getIcon(s.type)} {s.label}</div>))}</div>)}
                    </div>
                    <button onClick={handleGenerate} disabled={isLoading} className={`w-full ${isPremium ? 'bg-amber-500 hover:bg-amber-400' : 'bg-cyan-600 hover:bg-cyan-500'} text-black font-black py-4 rounded-xl flex items-center justify-center gap-3 tracking-[0.3em] text-[10px] transition-all shadow-lg`}>{isLoading ? <RefreshCw className="animate-spin" /> : <Zap size={16} />} GENERATE</button>
                  </div>
                </div>
              </div>
              <div className="lg:col-span-6 w-full">
                <div className="bg-slate-900/10 rounded-[3rem] flex flex-col min-h-[700px] shadow-2xl backdrop-blur-3xl overflow-hidden premium-border">
                  <div className={`px-8 py-6 border-b ${isPremium ? 'border-amber-900/30 bg-amber-950/10' : 'border-slate-800 bg-black/20'} flex justify-between items-center`}><div className="flex items-center gap-3"><div className={`w-2 h-2 rounded-full ${isPremium ? 'bg-amber-500 animate-pulse' : 'bg-emerald-500 animate-pulse'}`} /><span className={`text-[10px] font-black uppercase ${isPremium ? 'text-amber-500/60' : 'text-emerald-500/60'}`}>Neural_Output.json</span></div><button onClick={() => { navigator.clipboard.writeText(generatedPayload); showToast("COPIED!", "success"); }} disabled={!generatedPayload} className={`px-5 py-2 rounded-full text-[9px] font-black border ${isPremium ? 'border-amber-700 hover:bg-amber-500 text-amber-500' : 'border-slate-700 hover:bg-white text-white'} hover:text-black transition-all uppercase`}>COPY RAW</button></div>
                  <div className="flex-grow relative"><pre className={`absolute inset-0 p-8 font-mono text-[11px] ${isPremium ? 'text-amber-200' : 'text-emerald-400'} overflow-auto bg-black/40 text-left custom-scrollbar`}>{generatedPayload || "// System Standby..."}</pre></div>
                </div>
              </div>
              <div className="lg:col-span-3 w-full">
                <div className="flex items-center justify-between px-3 mb-2"><h3 className="text-[10px] font-black uppercase tracking-[0.4em] text-slate-500 flex items-center gap-2"><Archive size={14} /> ARCHIVES</h3></div>
                <div className="space-y-3 max-h-[650px] overflow-y-auto pr-2 custom-scrollbar">
                  {history.length === 0 ? <div className="p-10 border border-dashed border-slate-900 rounded-3xl text-center opacity-20"><Clock className="mx-auto mb-2" size={24}/><p className="text-[8px] font-black uppercase">No Archives</p></div> : history.map((item) => (
                    <div key={item.id} className={`group bg-slate-900/40 border ${isPremium ? 'border-amber-900/20 hover:border-amber-500' : 'border-slate-800 hover:border-cyan-500'} p-4 rounded-2xl cursor-pointer relative transition-all`}>
                      <div onClick={() => setGeneratedPayload(item.data)}><span className={`text-[8px] ${isPremium ? 'text-amber-700' : 'text-cyan-800'} font-black`}>{item.time}</span><h4 className="text-[10px] font-black uppercase truncate text-slate-300">{item.title}</h4><p className="text-[8px] text-slate-600 uppercase mt-1 italic">{item.style.split(' ')[0]} protocol</p></div>
                      <button onClick={(e) => { e.stopPropagation(); deleteHistory(item.id); }} className="absolute right-4 top-1/2 -translate-y-1/2 p-2 text-slate-800 hover:text-red-500 opacity-0 group-hover:opacity-100 transition-all"><Trash2 size={14} /></button>
                    </div>))}
                </div>
              </div>
            </div>
          </div>
        )}
      </div>
      {toast && <div className={`fixed bottom-10 left-1/2 -translate-x-1/2 px-8 py-3 rounded-full border shadow-2xl z-[1000] text-[10px] font-black tracking-widest uppercase animate-bounce ${toast.type === 'error' ? 'bg-red-950 border-red-500 text-red-100' : 'bg-cyan-950 border-cyan-500 text-cyan-100'}`}>{toast.message}</div>}
    </div>
  );
};

export default App;